### ISSUE TITLE
Object isnt working

### ISSUE THREAD

**Issue by delmenhorst** [sensel/PD-objects#1]
Hey,
I am on a Mac machine (MacOS 10.14) with pd vanilla and the object isnt loading.

is this object made for purr data? because I dont really understand the "l2ork_toggle_console 1" object?

the best, 
delmenhorst.

**Comment by mxa** [comment]
I can confirm that the compiled external from the repository is not loading in Pd 0.50 on Linux.

**Comment by mxa** [comment]
Seems it works now for me (haven't tested with the sensel yet).

**Comment by pd-l2ork** [comment]
Yes, the new release is now considered stable. I am closing this unless you encounter any further issues.
